# Use postgres/example user/password credentials
version: '3.1'
services:
  app:
    ports:
      - ${PORT}:${PORT}
    image: smliliia/app
    restart: always
    depends_on:
      - postgres
  postgres:
    image: smliliia/database
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSRTRES_DB: ${POSTGRES_DB}
