# Use postgres/example user/password credentials
version: '3.1'
services: 
  app:
    container_name: "app"
    ports:
      - ${PORT}:${PORT}
    image: smliliia/appdev
    restart: always
    volumes:
      - ./logs:/logs
      - ./src:/app/src
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
      container_name: "postgres"
      image: smliliia/database
      expose:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      restart: always
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U admin -d postgres"]
        interval: 10s
        timeout: 5s
        retries: 10
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSRTRES_DB: ${POSTGRES_DB}
